// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JustTalk.justTalkModels;

public partial class Archivemessage
{
    public long Id { get; set; }

    public long UserId { get; set; }

    public string MessageText { get; set; }

    public DateTime InsertedData { get; set; }
}