// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JustTalk.justTalkModels;

public partial class User
{
    public long Id { get; set; }

    public string Nick { get; set; }

    public string PlayableNick { get; set; }

    public string Password { get; set; }

    public DateTime UserCreated { get; set; }

    public DateTime UserLastTimeLogged { get; set; }

    public string Email { get; set; }
}